# GitHub Pages Configuration for EnterX
title: "EnterX - Modern Technical Solutions"
description: "EnterX delivers cutting-edge technical solutions and innovative software development services."
url: "https://rayuron.github.io"
baseurl: "/enterx"

# GitHub Pages settings
source: .
destination: ./_site
keep_files: [".git", ".svn"]
include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: "EnterX Team"
twitter:
  username: enterx
  card: summary_large_image

# Social media
social:
  name: EnterX
  links:
    - https://github.com/rayuron/enterx

# Default settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"